[package]
name = "pr_similarity_search"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tantivy = "0.21"
tokio = { version = "1.0", features = ["full"] }
octocrab = "0.32"